praekeltfoundation/healthcheckbot

- domain.yml
This adds a claim release to the 3 end messages, which should result in the conversation claim being released when combined with https://github.com/praekeltfoundation/turn-rasa-connector/pull/11
> Release claim at end of form

- .github/workflows/test.yaml
- actions/actions.py
- requirements-dev.txt
- tests/test_forms.py
The existing location pin formatting does not always result in a correctly formatted ISO6709 string expression. This PR aims so solve that
> Fix location pin formatting

- actions/actions.py
- tests/test_forms.py
This ensures that the location coordinates are always in the correct format when submitting to the eventstore
> Ensure location data is always submitted as ISO6709

- .github/workflows/build.yaml
- .github/workflows/test.yaml
- README.md
- dbe/actions/actions.py
- dbe/data/lookup_tables/ages.txt
- dbe/data/lookup_tables/gender.txt
- dbe/data/lookup_tables/provinces.txt
- dbe/data/nlu/address.md
- dbe/data/nlu/affirm.md
- dbe/data/nlu/chitchat.md
- dbe/data/nlu/deny.md
- dbe/data/nlu/exit.md
- dbe/data/nlu/healthcheck.md
- dbe/data/nlu/inform.md
- dbe/data/nlu/maybe.md
- dbe/data/nlu/more.md
- dbe/data/stories.md
- dbe/domain-eng.yml
- dbe/tests/conversation_tests.md
This adds a new bot for the Department of Basic Education, currently just a clone of the existing healthcheck.
It copies the domain file (no changes), imports the actions, and creates symlinks for the data
> Create a DBE bot, by cloning the existing bot

- dbe/actions/actions.py
- dbe/domain-eng.yml
- dbe/tests/test_actions.py
- setup.cfg
If there are no results for their school search, that could be because they selected the incorrect province. So we want to ask the province question again if there are no school results
> DBE Reask province on school error

- dbe/domain-eng.yml
Copy changes to ensure copy is the same as in the sheet https://docs.google.com/spreadsheets/d/1cVjPb-ae1qOh4wxJ2skm0kS4QrUoCp9opm9Pqd59VGc/edit#gid=861878833
> DBE copy changes

- base/actions/actions.py
- dbe/actions/actions.py
- dbe/data/lookup_tables/profiles.txt
- dbe/domain-eng.yml
- dbe/tests/test_actions.py
This will allow the user to type "Other" instead of searching for a school
> Add other option for school

- dbe/actions/actions.py
- dbe/domain-eng.yml
- dbe/tests/test_actions.py
This adds the information confirmation for returning users.
Allowing the user to change any values will be done in a separate PR
> Add confirmation question for returning users

- dbe/actions/actions.py
- dbe/domain-eng.yml
- dbe/tests/test_actions.py
If a returning user says that the info is incorrect, this will allow them to correct it
> Allow returning users to change province or school

- dbe/actions/actions.py
- dbe/domain-eng.yml
- dbe/tests/test_actions.py
There doesn't seem to be an easy way to "clear all slots" in a form field validation, so unfortunately it's a bit messy, but not sure how else to do this
> Option to change cadre

- hh/actions/import_university_data.py
- hh/actions/university_data.yaml
- hh/tests/test_import_university_data.py
This PR has 2 commits.
The first commit just sorts the university data yaml file
The second one updates the script to always insert in sorted order
There was no data added/removed/changed in this PR. This just sorts every thing to make it easier to see in the future what the changes were when we do import new data.
> Sort university data on import

- base/actions/actions.py
- dbe/actions/actions.py
- dbe/domain-eng.yml
- dbe/tests/test_actions.py
- dbe/tests/test_forms.py
This adds additional comorbidity questions. Everyone should be asked them. Pregnancy question should only be asked to people who answered >12 years of age and female.
> Expanded comorbidities

- base/actions/actions.py
- base/tests/test_forms.py
- dbe/tests/test_import_school_data.py
This makes sure that we're actually covering all the important things with unit tests
Before:
```
Name                                   Stmts   Miss  Cover
----------------------------------------------------------
base/actions/__init__.py                   0      0   100%
base/actions/actions.py                  243     40    84%
base/actions/config.py                     6      0   100%
base/actions/utils.py                     19      0   100%
dbe/actions/__init__.py                    0      0   100%
dbe/actions/actions.py                   227     11    95%
dbe/actions/import_school_data.py         29     29     0%
dbe/actions/utils.py                      36      1    97%
hh/actions/__init__.py                     0      0   100%
hh/actions/actions.py                    100      5 …
```
> Add more unit test coverage

- dbe/actions/actions.py
- dbe/domain-eng.yml
Change pregnancy question age to include 12, and some copy fixes
> DBE changes

- dbe/actions/actions.py
- dbe/domain-eng.yml
- dbe/tests/test_actions.py
- setup.cfg
seems like my editor also removed some trailing spaces
> Update risk copy for support profile

- dbe/actions/actions.py
- dbe/data/lookup_tables/profiles.txt
- dbe/domain-eng.yml
- dbe/tests/test_actions.py
This profile needs to be able to search across both the list of schools and the list of marking centers
> Add National DBE staff profile

- hh/actions/actions.py
- hh/domain-eng.yml
- hh/tests/test_actions.py
Adds text search for finding an institution from the list
> Add search for institution list

- hh/actions/actions.py
- hh/tests/test_actions.py
We need to set the `campus_list` slot, for the list of campuses to display properly
> Fix campus list

- base/domain-eng.yml
- hh/domain-eng.yml
Government guidelines have changed, this PR changes the result copy to be in-line with the new guidelines
﻿- Update base healthcheck copy
- Update copy on higherhealth healthcheck
> Update HealthCheck result copy

- hh/domain-eng.yml
New regulations require that for moderate risk, students are still allowed to access campus
> Show green success for moderate risk

- hh/actions/actions.py
- hh/data/stories.md
- hh/domain-eng.yml
- hh/tests/conversation_tests.md
- hh/tests/test_actions.py
* Fix to use correct province slot
* Adds a pre-healthcheck call to `covid19triagestart`
* Adds start timestamp to json data on healthcheck completion.
> Add start timestamp so that ds can calculate duration
